{% set name = "sagenb" %}
{% set version = "1.1.1" %}
{% set hash = "a6740bc2b2b331a6adbb865be2bf76c6bf6ef1630fc16be1879bcc16530fe00c" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/sagenb/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed . --verbose

requirements:
  host:
    - python
    - pip

  run:
    - python
    - twisted >=11.0.0
    - flask >=0.10.1,<0.12
    - flask-oldsessions >=0.10
    - flask-openid
    - flask-autoindex
    - flask-babel 0.9

test:
  commands:
    # Can't import sagenb as it depends on sage and sage depends on sagenb
    - test -f $SP_DIR/sagenb/__init__.py                    # [unix]
    - if not exist %SP_DIR%\\sagenb\\__init__.py exit 1     # [win]

about:
  home: https://github.com/sagemath/sagenb
  license_file: COPYING
  license: GPLv3+
  license_family: GPL
  summary: 'The Sage Notebook'
  dev_url: https://github.com/sagemath/sagenb

extra:
  recipe-maintainers:
    - isuruf
