travis:
  secure:
    BINSTAR_TOKEN: AniO38gD7wwFLQ1Zn9155vw3ajvd14GizRuZ1Ovqf4NVqDjf2oamnx12yWPA3N72ShXDRh3h8AxmIxdd+WxnSoT/82Fur1eEL85ajFgrk/vbGH70DBexPtNesiiq1z623XhQdkU5jaSjghUCYxNsEg4lo/ibUd7vDF/I8ve7wfRE7c6+657gbgS1MojdMnWn8oBzQhQUVn8Ey59mA39NgmZihoUsRacUYIBIhclUZ3vyhRbWxALZGJyJRNN9BPGbEg4mm8T4iONIPja86aBXQh89HQvW7+y7tUI0ipqfjxG/Gbi/9awKsvY8AvPBDUQ5v1SNAvTPBTyDRtAhF63iuOFIY4k6dW6YBGQWZ8OAKBmuSljlZ0SHdyY84Xdr/v31tFM173GvZbPPlltL3hOAqGsarVtyX0kdWLaP5JLdZ9kPiKc5vlMs/K0EB4pBFhNYViWPCJ5EoNLAm9SM2rCig3O9tF0s2BmYahgbfODFxKlBtkiBwuPSmi/YXJ0wDPu4ASbdS1SUMetP/TWq+eoxUqx/PN+PJqHXZWqeXgJ99e27K3475p3892uf8SFhS0EWNLPRmfUe4oVNREBX10cWzS8Ta2kX4DYUXu9JzwbHev/x+L8jT0MCTzroxg6Db31kzdLkUNgonZipvhD5ipjMJi5/ph7G2Fs+DP3ed5j3Zlo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
