travis:
  secure:
    BINSTAR_TOKEN: nT9kbgHMoZI7vo+61Xk4KCWehjIL16zK7CkepTin7jgVmoD3ew5I5xURt/+d9+L3aQpz7Oe4GJMKVCJGpk+aiOn0ZG2Qp1vBx/ybfEfGMEDV758lpwX/VTYXqLiBQQ+uuKlv93VChlJlf5R52GnIr6OPB5WKSAB2Jka7oKXaQlUsAWcrNuNg4fVM79p1sXlwBLKP9j98SdBrytg+a8s//eYyq9PxbMe0daftxhfgFpqPIMHbMzfbd2wzNzUTQUVChA+jHz1RjXgJijvra1c6rGthHji6Y5pCWF+zvaTLPwr8CE5Z5Vck/SnOQ/eKRSo9U8d9aNS/0qbR3RSPe7z8PMzlKOTgytOaqCjyzR4LH11et5oRfpz5Bw698AiVhYxi6fL1sd5bVY+pvrfLiGKpem9Nj3LRFoEU3NYTGDh0b3cjZBRl3gBNnG8nqsk7njdY67OgWP7V9H9N3JWshdcUUV9iyCm14vRrBbKmxucfL7sXDv3jCFWAxsYFxFc9fG0NraIBZepM/UeH8D7KIWipgraO8VdyfUQA/JViX2/YHxCU1xPhx42xOtBXjVkUkw9xVeWyVLpuHuKLA4rFZLOKN5JrWWUY67D+jSbqWzmwWCs6Nk4xQ3+eeRBoZ/sF/pmq2eDzhnKydfrbANsIkfpiFv8qsW2r3bJM281FzUVe3lQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
