travis:
  secure:
    BINSTAR_TOKEN: GdEbhHtWZbAnEvjISuSyGSlUBM1cG80S+4bwISpw4Zvg3q+2Yli9TUX5PYoojIYsDG/wNQtoI2FdvfNbT9YsKTzPn2Aa5OMl031DFMb4zD7R9pt5HRdwXbRxFwmXUluqokvn8rWR+dQpdQSeDEMCofSU8kinEr/Z2h9Wu7D5GeNxtvR25mkTWMSen0MGPubFWn4Q8zbMFzV5y8IriBquxrMnlrJ9LDFemqigqPhWUxcIjXeVz52I4GI0/EyDPrYmPI3ml+jyJtWDx1Pf146CAzvUOdn3A7V9PuHX43Ooxvn4ezKgFuYVJEfxv/OlkPv+kdZfTynS21weu78Wwu+O71XlvP6Jm1Xi0r+AEtLSEci4kaO1kbgL1rD31VMoM32xVI7LIIr3il9D+uyS9pv15ZeDq9qtv7e4KtbJ7PJncp5u64vF52Y+OvveRLGKtdJ3QfhikBJ0QpsPlbR5ZO16nVMxsZujCwu90HZZkN2bCTYNb5IVOJ67ef91ea/f/q7tSCTL2ajL3GxQYs8YPcfxE3uELlNl/6AwyhaPmSR0oq4Z0BqPo3TBunhLe8c7NsbW27zJRX8/FFYVcXXRI3USM42RgpdN1rbbl7bQtoc8a+aCGdSmTSU2ZSUoYkUBnDFrEHH6eyHbypRtd8ZGGx59yHBmq1bm7WyZkcbMPV2SuA8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
